// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: CarControlUI

#include "ui.h"
#include "ui_helpers.h"
 int flag=0 ;
///////////////////// VARIABLES ////////////////////
void show_Animation(lv_obj_t * TargetObject, int delay);
lv_obj_t * ui_Screen1;
void ui_event_RotateSlider(lv_event_t * e);
lv_obj_t * ui_RotateSlider;
void ui_event_SpeedSlider(lv_event_t * e);
lv_obj_t * ui_SpeedSlider;
lv_obj_t * ui_RotateLabel;
lv_obj_t * ui_SpeedLabel;
lv_obj_t * ui_Oil;
lv_obj_t * ui_Right;
lv_obj_t * ui_Left;
void ui_event_Wwiper(lv_event_t * e);
lv_obj_t * ui_Wwiper;
lv_obj_t * ui_Image;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_[3] = {&ui_img_0_png, &ui_img_1_png, &ui_img_2_png};
const lv_img_dsc_t * ui_imgset_audio_wave_[1] = {&ui_img_audio_wave_1_png};
const lv_img_dsc_t * ui_imgset_car_speed[2] = {&ui_img_car_speed1_png, &ui_img_car_speed2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void show_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->imgset = ui_imgset_;
    PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_) / (sizeof(lv_img_dsc_t *));
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 5);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->imgset = ui_imgset_;
    PropertyAnimation_1_user_data->imgset_size = sizeof(ui_imgset_) / (sizeof(lv_img_dsc_t *));
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_1, 5, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_RotateSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_RotateLabel, target, "", "");
    }
}
void ui_event_SpeedSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_text_value(ui_SpeedLabel, target, "", "");
    }
}
void ui_event_Wwiper(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        //_ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
       flag = 1;
    }
    else{
       flag = 0;
   }
}

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_car_ui__png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RotateSlider = lv_slider_create(ui_Screen1);
    lv_obj_set_width(ui_RotateSlider, 211);
    lv_obj_set_height(ui_RotateSlider, 236);
    lv_obj_set_x(ui_RotateSlider, -130);
    lv_obj_set_y(ui_RotateSlider, -6);
    lv_obj_set_align(ui_RotateSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_RotateSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RotateSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RotateSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RotateSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RotateSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_RotateSlider, &ui_img_car_speed1_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RotateSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RotateSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RotateSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SpeedSlider = lv_slider_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedSlider, 211);
    lv_obj_set_height(ui_SpeedSlider, 236);
    lv_obj_set_x(ui_SpeedSlider, 139);
    lv_obj_set_y(ui_SpeedSlider, -4);
    lv_obj_set_align(ui_SpeedSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SpeedSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SpeedSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpeedSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SpeedSlider, &ui_img_car_speed2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SpeedSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpeedSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_RotateLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RotateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RotateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RotateLabel, -151);
    lv_obj_set_y(ui_RotateLabel, -1);
    lv_obj_set_align(ui_RotateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RotateLabel, "0");
    lv_obj_set_style_text_color(ui_RotateLabel, lv_color_hex(0x4BE0DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RotateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RotateLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLabel, 117);
    lv_obj_set_y(ui_SpeedLabel, 0);
    lv_obj_set_align(ui_SpeedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedLabel, "0");
    lv_obj_set_style_text_color(ui_SpeedLabel, lv_color_hex(0x4BE0DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Oil = lv_slider_create(ui_Screen1);
    lv_obj_set_width(ui_Oil, 106);
    lv_obj_set_height(ui_Oil, 109);
    lv_obj_set_x(ui_Oil, 0);
    lv_obj_set_y(ui_Oil, -7);
    lv_obj_set_align(ui_Oil, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Oil, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Oil, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Oil, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Oil, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Oil, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Oil, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Oil, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Right = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Right, &ui_img_2_png);
    lv_obj_set_width(ui_Right, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Right, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Right, 97);
    lv_obj_set_y(ui_Right, -73);
    lv_obj_set_align(ui_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Left = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Left, &ui_img_1_png);
    lv_obj_set_width(ui_Left, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Left, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Left, -106);
    lv_obj_set_y(ui_Left, -75);
    lv_obj_set_align(ui_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Left, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wwiper = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Wwiper, 50);
    lv_obj_set_height(ui_Wwiper, 25);
    lv_obj_set_x(ui_Wwiper, 166);
    lv_obj_set_y(ui_Wwiper, 75);
    lv_obj_set_align(ui_Wwiper, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Wwiper, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wwiper, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Wwiper, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wwiper, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Wwiper, lv_color_hex(0x42AFAE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wwiper, 100, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Wwiper, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Wwiper, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image, &ui_img_0_png);
    lv_obj_set_width(ui_Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image, -180);
    lv_obj_set_y(ui_Image, 126);
    lv_obj_set_align(ui_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_RotateSlider, ui_event_RotateSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SpeedSlider, ui_event_SpeedSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wwiper, ui_event_Wwiper, LV_EVENT_ALL, NULL);

}

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
