// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: CarControlUI

#ifndef _CARCONTROLUI_UI_H
#define _CARCONTROLUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
void show_Animation(lv_obj_t * TargetObject, int delay);
extern lv_obj_t * ui_Screen1;
void ui_event_RotateSlider(lv_event_t * e);
extern lv_obj_t * ui_RotateSlider;
void ui_event_SpeedSlider(lv_event_t * e);
extern lv_obj_t * ui_SpeedSlider;
extern lv_obj_t * ui_RotateLabel;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_Oil;
extern lv_obj_t * ui_Right;
extern lv_obj_t * ui_Left;
void ui_event_Wwiper(lv_event_t * e);
extern lv_obj_t * ui_Wwiper;
extern lv_obj_t * ui_Image;
extern lv_obj_t * ui____initial_actions0;
extern int flag ;

LV_IMG_DECLARE(ui_img_car_ui__png);    // assets\Car UI .png
LV_IMG_DECLARE(ui_img_car_speed1_png);    // assets\car speed1.png
LV_IMG_DECLARE(ui_img_car_speed2_png);    // assets\car speed2.png
LV_IMG_DECLARE(ui_img_2_png);    // assets\2.png
LV_IMG_DECLARE(ui_img_1_png);    // assets\1.png
LV_IMG_DECLARE(ui_img_0_png);    // assets\0.png
LV_IMG_DECLARE(ui_img_audio_wave_1_png);    // assets\audio_wave_1.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
