// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project-test

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
void ui_event_AX(lv_event_t * e);
lv_obj_t * ui_AX;
lv_obj_t * ui_TextArea7;
lv_obj_t * ui_TextArea8;
lv_obj_t * ui_TextArea9;
lv_obj_t * ui_Keyboard1;
void ui_event_AN(lv_event_t * e);
lv_obj_t * ui_AN;
void ui_event_DN(lv_event_t * e);
lv_obj_t * ui_DN;
void ui_event_DX(lv_event_t * e);
lv_obj_t * ui_DX;
void ui_event_IN(lv_event_t * e);
lv_obj_t * ui_IN;
void ui_event_IX(lv_event_t * e);
lv_obj_t * ui_IX;
lv_obj_t * ui_Tem;
lv_obj_t * ui_Light;
lv_obj_t * ui_Label;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_[1] = {&ui_img_1_png};
const lv_img_dsc_t * ui_imgset_smart[1] = {&ui_img_smart1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_AX(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_AX);
    }
}
void ui_event_AN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_AN);
    }
}
void ui_event_DN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_DN);
    }
}
void ui_event_DX(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_DX);
    }
}
void ui_event_IN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_IN);
    }
}
void ui_event_IX(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_IX);
    }
}

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_smart1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AX = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_AX, 51);
    lv_obj_set_height(ui_AX, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_AX, -58);
    lv_obj_set_y(ui_AX, -30);
    lv_obj_set_align(ui_AX, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_AX, "100");
    lv_textarea_set_one_line(ui_AX, true);

    ui_TextArea7 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea7, 70);
    lv_obj_set_height(ui_TextArea7, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_TextArea7, 140);
    lv_obj_set_y(ui_TextArea7, 40);
    lv_obj_set_align(ui_TextArea7, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_TextArea7, true);

    ui_TextArea8 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea8, 70);
    lv_obj_set_height(ui_TextArea8, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_TextArea8, 140);
    lv_obj_set_y(ui_TextArea8, 87);
    lv_obj_set_align(ui_TextArea8, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_TextArea8, true);

    ui_TextArea9 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea9, 70);
    lv_obj_set_height(ui_TextArea9, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_TextArea9, 140);
    lv_obj_set_y(ui_TextArea9, 134);
    lv_obj_set_align(ui_TextArea9, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_TextArea9, true);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 474);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, -1);
    lv_obj_set_y(ui_Keyboard1, 97);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AN = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_AN, 51);
    lv_obj_set_height(ui_AN, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_AN, -179);
    lv_obj_set_y(ui_AN, -30);
    lv_obj_set_align(ui_AN, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_AN, "0");
    lv_textarea_set_one_line(ui_AN, true);

    ui_DN = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_DN, 51);
    lv_obj_set_height(ui_DN, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_DN, 61);
    lv_obj_set_y(ui_DN, -30);
    lv_obj_set_align(ui_DN, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_DN, "20");
    lv_textarea_set_one_line(ui_DN, true);

    ui_DX = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_DX, 51);
    lv_obj_set_height(ui_DX, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_DX, 184);
    lv_obj_set_y(ui_DX, -31);
    lv_obj_set_align(ui_DX, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_DX, "40");
    lv_textarea_set_one_line(ui_DX, true);

    ui_IN = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_IN, 51);
    lv_obj_set_height(ui_IN, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_IN, -177);
    lv_obj_set_y(ui_IN, 133);
    lv_obj_set_align(ui_IN, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_IN, "0");
    lv_textarea_set_one_line(ui_IN, true);

    ui_IX = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_IX, 51);
    lv_obj_set_height(ui_IX, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_IX, -56);
    lv_obj_set_y(ui_IX, 133);
    lv_obj_set_align(ui_IX, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_IX, "500");
    lv_textarea_set_one_line(ui_IX, true);

    ui_Tem = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Tem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Tem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Tem, 126);
    lv_obj_set_y(ui_Tem, -93);
    lv_obj_set_align(ui_Tem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Tem, "0");
    lv_obj_add_flag(ui_Tem, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Light = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Light, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Light, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Light, -117);
    lv_obj_set_y(ui_Light, 68);
    lv_obj_set_align(ui_Light, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Light, "0");
    lv_obj_set_style_text_font(ui_Light, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label, -127);
    lv_obj_set_y(ui_Label, -91);
    lv_obj_set_align(ui_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label, "0");
    lv_obj_add_flag(ui_Label, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_AX, ui_event_AX, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_AX);
    lv_obj_add_event_cb(ui_AN, ui_event_AN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DN, ui_event_DN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DX, ui_event_DX, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IN, ui_event_IN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IX, ui_event_IX, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
