// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project-test

#ifndef _SQUARELINE_PROJECT_TEST_UI_H
#define _SQUARELINE_PROJECT_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_events.h"
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
void ui_event_AX(lv_event_t * e);
extern lv_obj_t * ui_AX;
extern lv_obj_t * ui_TextArea7;
extern lv_obj_t * ui_TextArea8;
extern lv_obj_t * ui_TextArea9;
extern lv_obj_t * ui_Keyboard1;
void ui_event_AN(lv_event_t * e);
extern lv_obj_t * ui_AN;
void ui_event_DN(lv_event_t * e);
extern lv_obj_t * ui_DN;
void ui_event_DX(lv_event_t * e);
extern lv_obj_t * ui_DX;
void ui_event_IN(lv_event_t * e);
extern lv_obj_t * ui_IN;
void ui_event_IX(lv_event_t * e);
extern lv_obj_t * ui_IX;
extern lv_obj_t * ui_Tem;
extern lv_obj_t * ui_Light;
extern lv_obj_t * ui_Label;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_smart1_png);    // assets\smart1.png
LV_IMG_DECLARE(ui_img_1_png);    // assets\1.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
