// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Mixer

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Fadeoff_Animation(lv_obj_t * TargetObject, int delay);
void Fadeon_Animation(lv_obj_t * TargetObject, int delay);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Background;
lv_obj_t * ui_Display;
lv_obj_t * ui_Label_artist;
lv_obj_t * ui_Label_song;
lv_obj_t * ui_Label_time;
lv_obj_t * ui_Slider_Wave;
void ui_event_BTN_EQ(lv_event_t * e);
lv_obj_t * ui_BTN_EQ;
lv_obj_t * ui_Left_Group;
lv_obj_t * ui_MIN;
lv_obj_t * ui_MAX;
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Right_Group;
lv_obj_t * ui_MIN1;
lv_obj_t * ui_MAX1;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_BNT_Play;
lv_obj_t * ui_EQ;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Arc2;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Slider4;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_audio_wave_[1] = {&ui_img_audio_wave_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Fadeoff_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 100);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 300, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void Fadeon_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 100);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 300);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_BTN_EQ(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_Slider4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_EQ, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        Fadeoff_Animation(ui_EQ, 0);
        Fadeoff_Animation(ui_Slider4, 0);
        Fadeon_Animation(ui_BNT_Play, 0);
        Fadeon_Animation(ui_Left_Group, 0);
        Fadeon_Animation(ui_Right_Group, 0);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_EQ, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Slider4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        Fadeon_Animation(ui_EQ, 0);
        Fadeon_Animation(ui_Slider4, 0);
        Fadeoff_Animation(ui_BNT_Play, 0);
        Fadeoff_Animation(ui_Left_Group, 0);
        Fadeoff_Animation(ui_Right_Group, 0);
    }
}

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Screen1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Background = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Background, 320);
    lv_obj_set_height(ui_Background, 480);
    lv_obj_set_align(ui_Background, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Background, lv_color_hex(0x424143), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Background, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display = lv_obj_create(ui_Background);
    lv_obj_set_width(ui_Display, 280);
    lv_obj_set_height(ui_Display, 112);
    lv_obj_set_x(ui_Display, 1);
    lv_obj_set_y(ui_Display, -168);
    lv_obj_set_align(ui_Display, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Display, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display, lv_color_hex(0x2D2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_artist = lv_label_create(ui_Display);
    lv_obj_set_width(ui_Label_artist, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_artist, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_artist, -103);
    lv_obj_set_y(ui_Label_artist, -11);
    lv_obj_set_align(ui_Label_artist, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_artist, "SKY");
    lv_obj_set_style_text_color(ui_Label_artist, lv_color_hex(0x938A8A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_artist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_song = lv_label_create(ui_Display);
    lv_obj_set_width(ui_Label_song, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_song, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_song, -83);
    lv_obj_set_y(ui_Label_song, -34);
    lv_obj_set_align(ui_Label_song, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_song, "Monsters");
    lv_obj_set_style_text_color(ui_Label_song, lv_color_hex(0xF7F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_song, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_time = lv_label_create(ui_Display);
    lv_obj_set_width(ui_Label_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_time, 21);
    lv_obj_set_y(ui_Label_time, -24);
    lv_obj_set_align(ui_Label_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_time, "03:25");
    lv_obj_set_style_text_color(ui_Label_time, lv_color_hex(0xF5F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_time, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider_Wave = lv_slider_create(ui_Display);
    lv_obj_set_width(ui_Slider_Wave, 168);
    lv_obj_set_height(ui_Slider_Wave, 59);
    lv_obj_set_x(ui_Slider_Wave, -35);
    lv_obj_set_y(ui_Slider_Wave, 27);
    lv_obj_set_align(ui_Slider_Wave, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider_Wave, lv_color_hex(0x2D2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Wave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider_Wave, &ui_img_audio_wave_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_Wave, lv_color_hex(0x2D2A2A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Wave, 150, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_Wave, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Wave, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BTN_EQ = lv_imgbtn_create(ui_Display);
    lv_imgbtn_set_src(ui_BTN_EQ, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_eq_inact_png, NULL);
    lv_imgbtn_set_src(ui_BTN_EQ, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_eq_act_png, NULL);
    lv_imgbtn_set_src(ui_BTN_EQ, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_eq_inact_png, NULL);
    lv_imgbtn_set_src(ui_BTN_EQ, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_eq_act_png, NULL);
    lv_imgbtn_set_src(ui_BTN_EQ, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_eq_act_png, NULL);
    lv_imgbtn_set_src(ui_BTN_EQ, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_eq_inact_png, NULL);
    lv_obj_set_height(ui_BTN_EQ, 99);
    lv_obj_set_width(ui_BTN_EQ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_BTN_EQ, 95);
    lv_obj_set_y(ui_BTN_EQ, 6);
    lv_obj_set_align(ui_BTN_EQ, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_EQ, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_Left_Group = lv_obj_create(ui_Background);
    lv_obj_set_width(ui_Left_Group, 121);
    lv_obj_set_height(ui_Left_Group, 355);
    lv_obj_set_x(ui_Left_Group, 0);
    lv_obj_set_y(ui_Left_Group, 20);
    lv_obj_set_align(ui_Left_Group, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_Left_Group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Left_Group, lv_color_hex(0x424143), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Left_Group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Left_Group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Left_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Left_Group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Left_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Left_Group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Left_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MIN = lv_label_create(ui_Left_Group);
    lv_obj_set_width(ui_MIN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MIN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MIN, -11);
    lv_obj_set_y(ui_MIN, 139);
    lv_obj_set_align(ui_MIN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MIN, "MIN");
    lv_obj_set_style_text_color(ui_MIN, lv_color_hex(0xEAE1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MIN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MAX = lv_label_create(ui_Left_Group);
    lv_obj_set_width(ui_MAX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MAX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MAX, -13);
    lv_obj_set_y(ui_MAX, -167);
    lv_obj_set_align(ui_MAX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MAX, "mAX");
    lv_obj_set_style_text_color(ui_MAX, lv_color_hex(0xEFE4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MAX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Left_Group);
    lv_obj_set_width(ui_Slider2, 65);
    lv_obj_set_height(ui_Slider2, 267);
    lv_obj_set_x(ui_Slider2, -10);
    lv_obj_set_y(ui_Slider2, -13);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider2, &ui_img_pot_ver_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider2, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider2, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider2, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider2, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider2, 12, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider2, &ui_img_pot_ver_knob_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider2, 100, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider2, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Slider2, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Slider2, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider2, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider2, 6, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider2, 6, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Right_Group = lv_obj_create(ui_Background);
    lv_obj_set_width(ui_Right_Group, 84);
    lv_obj_set_height(ui_Right_Group, 355);
    lv_obj_set_x(ui_Right_Group, 0);
    lv_obj_set_y(ui_Right_Group, 22);
    lv_obj_set_align(ui_Right_Group, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Right_Group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Right_Group, lv_color_hex(0x424143), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Right_Group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Right_Group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Right_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Right_Group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Right_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Right_Group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Right_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MIN1 = lv_label_create(ui_Right_Group);
    lv_obj_set_width(ui_MIN1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MIN1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MIN1, -2);
    lv_obj_set_y(ui_MIN1, 136);
    lv_obj_set_align(ui_MIN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MIN1, "MIN");
    lv_obj_set_style_text_color(ui_MIN1, lv_color_hex(0xEAE1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MIN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MAX1 = lv_label_create(ui_Right_Group);
    lv_obj_set_width(ui_MAX1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MAX1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MAX1, -2);
    lv_obj_set_y(ui_MAX1, -168);
    lv_obj_set_align(ui_MAX1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MAX1, "MAX");
    lv_obj_set_style_text_color(ui_MAX1, lv_color_hex(0xEFE4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MAX1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Right_Group);
    lv_obj_set_width(ui_Slider1, 65);
    lv_obj_set_height(ui_Slider1, 267);
    lv_obj_set_x(ui_Slider1, -4);
    lv_obj_set_y(ui_Slider1, -13);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider1, &ui_img_pot_ver_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider1, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider1, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider1, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider1, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider1, 12, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider1, &ui_img_pot_ver_knob_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider1, 100, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider1, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Slider1, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Slider1, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider1, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider1, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider1, 6, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider1, 6, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BNT_Play = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_BNT_Play, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_play_inact_png, NULL);
    lv_imgbtn_set_src(ui_BNT_Play, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_play_act_png, NULL);
    lv_imgbtn_set_src(ui_BNT_Play, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_btn_play_inact_png, NULL);
    lv_imgbtn_set_src(ui_BNT_Play, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_play_act_png, NULL);
    lv_imgbtn_set_src(ui_BNT_Play, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_play_act_png, NULL);
    lv_imgbtn_set_src(ui_BNT_Play, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_btn_play_inact_png, NULL);
    lv_obj_set_height(ui_BNT_Play, 155);
    lv_obj_set_width(ui_BNT_Play, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_BNT_Play, 4);
    lv_obj_set_y(ui_BNT_Play, 66);
    lv_obj_set_align(ui_BNT_Play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BNT_Play, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_EQ = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_EQ, 250);
    lv_obj_set_height(ui_EQ, 159);
    lv_obj_set_x(ui_EQ, -1);
    lv_obj_set_y(ui_EQ, 4);
    lv_obj_set_align(ui_EQ, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EQ, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_EQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EQ, lv_color_hex(0x424143), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_EQ);
    lv_img_set_src(ui_Image2, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_Image2, 105);
    lv_obj_set_height(ui_Image2, 104);
    lv_obj_set_x(ui_Image2, -50);
    lv_obj_set_y(ui_Image2, -17);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_EQ);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -50);
    lv_obj_set_y(ui_Label2, 52);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "LOW");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xF7EEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_EQ);
    lv_obj_set_width(ui_Arc2, 94);
    lv_obj_set_height(ui_Arc2, 95);
    lv_obj_set_x(ui_Arc2, -50);
    lv_obj_set_y(ui_Arc2, -16);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_obj_set_style_pad_left(ui_Arc2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Arc2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Arc2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Arc2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_EQ);
    lv_img_set_src(ui_Image1, &ui_img_btn_knob_png);
    lv_obj_set_width(ui_Image1, 105);
    lv_obj_set_height(ui_Image1, 104);
    lv_obj_set_x(ui_Image1, 68);
    lv_obj_set_y(ui_Image1, -15);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_EQ);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 69);
    lv_obj_set_y(ui_Label1, 51);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "HIGH");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xF7EEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_EQ);
    lv_obj_set_width(ui_Arc1, 94);
    lv_obj_set_height(ui_Arc1, 95);
    lv_obj_set_x(ui_Arc1, 71);
    lv_obj_set_y(ui_Arc1, -14);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_set_style_pad_left(ui_Arc1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Arc1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Arc1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Arc1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider4 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider4, -100, 100);
    lv_slider_set_mode(ui_Slider4, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_Slider4, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 274);
    lv_obj_set_height(ui_Slider4, 82);
    lv_obj_set_x(ui_Slider4, -1);
    lv_obj_set_y(ui_Slider4, 156);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider4, &ui_img_pot_hor_line_tempo_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider4, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider4, 35, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider4, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 222, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider4, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider4, 22, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider4, 12, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider4, &ui_img_pot_hor_knob_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider4, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider4, 100, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider4, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Slider4, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Slider4, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider4, -1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider4, -1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider4, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider4, -4, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTN_EQ, ui_event_BTN_EQ, LV_EVENT_ALL, NULL);

}

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
