// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Mixer

#ifndef _MIXER_UI_H
#define _MIXER_UI_H

#ifdef __cplusplus
extern "C" {
#endif
#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
void Fadeoff_Animation(lv_obj_t * TargetObject, int delay);
void Fadeon_Animation(lv_obj_t * TargetObject, int delay);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Background;
extern lv_obj_t * ui_Display;
extern lv_obj_t * ui_Label_artist;
extern lv_obj_t * ui_Label_song;
extern lv_obj_t * ui_Label_time;
extern lv_obj_t * ui_Slider_Wave;
void ui_event_BTN_EQ(lv_event_t * e);
extern lv_obj_t * ui_BTN_EQ;
extern lv_obj_t * ui_Left_Group;
extern lv_obj_t * ui_MIN;
extern lv_obj_t * ui_MAX;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Right_Group;
extern lv_obj_t * ui_MIN1;
extern lv_obj_t * ui_MAX1;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_BNT_Play;
extern lv_obj_t * ui_EQ;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_audio_wave_1_png);    // assets\audio_wave_1.png
LV_IMG_DECLARE(ui_img_btn_eq_inact_png);    // assets\btn_eq_inact.png
LV_IMG_DECLARE(ui_img_btn_eq_act_png);    // assets\btn_eq_act.png
LV_IMG_DECLARE(ui_img_pot_ver_line_png);    // assets\pot_ver_line.png
LV_IMG_DECLARE(ui_img_pot_ver_knob_png);    // assets\pot_ver_knob.png
LV_IMG_DECLARE(ui_img_btn_play_inact_png);    // assets\btn_play_inact.png
LV_IMG_DECLARE(ui_img_btn_play_act_png);    // assets\btn_play_act.png
LV_IMG_DECLARE(ui_img_btn_knob_png);    // assets\btn_knob.png
LV_IMG_DECLARE(ui_img_pot_hor_line_tempo_png);    // assets\pot_hor_line_tempo.png
LV_IMG_DECLARE(ui_img_pot_hor_knob_png);    // assets\pot_hor_knob.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
