// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Control

#ifndef _CONTROL_UI_H
#define _CONTROL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui____initial_actions0;
extern int flag ;

LV_IMG_DECLARE(ui_img_pot_ver_knob_png);    // assets\pot_ver_knob.png
LV_IMG_DECLARE(ui_img_light_off__png);    // assets\light off .png
LV_IMG_DECLARE(ui_img_light_on__png);    // assets\Light On .png
LV_IMG_DECLARE(ui_img_audio_wave_1_png);    // assets\audio_wave_1.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
