// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: Text

#ifndef _TEXT_UI_H
#define _TEXT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Keyboard2;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_boy_png);    // assets\boy.png
LV_IMG_DECLARE(ui_img_audio_wave_1_png);    // assets\audio_wave_1.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
