// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: Text

#include "ui.h"

void ui_comp_Button2_create_hook(lv_obj_t * comp)
{
}
