// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: rgb1

#ifndef _RGB1_UI_H
#define _RGB1_UI_H

#ifdef __cplusplus
extern "C" {
#endif
#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
void ui_event_red(lv_event_t * e);
extern lv_obj_t * ui_red;
void ui_event_blue(lv_event_t * e);
extern lv_obj_t * ui_blue;
void ui_event_orange(lv_event_t * e);
extern lv_obj_t * ui_orange;
void ui_event_yellow(lv_event_t * e);
extern lv_obj_t * ui_yellow;
void ui_event_green(lv_event_t * e);
extern lv_obj_t * ui_green;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui____initial_actions0;
extern int flag ;

LV_IMG_DECLARE(ui_img_red_png);    // assets\red.png
LV_IMG_DECLARE(ui_img_blue_png);    // assets\blue.png
LV_IMG_DECLARE(ui_img_orange_png);    // assets\orange.png
LV_IMG_DECLARE(ui_img_yellow_png);    // assets\yellow.png
LV_IMG_DECLARE(ui_img_greend_png);    // assets\greend.png
LV_IMG_DECLARE(ui_img_audio_wave_1_png);    // assets\audio_wave_1.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
