// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: rgb1

#ifndef _RGB1_UI_H
#define _RGB1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
void ui_event_red(lv_event_t * e);
extern lv_obj_t * ui_red;
void ui_event_green(lv_event_t * e);
extern lv_obj_t * ui_green;
void ui_event_blue(lv_event_t * e);
extern lv_obj_t * ui_blue;
extern lv_obj_t * ui____initial_actions0;
extern int flag ;

LV_IMG_DECLARE(ui_img_red_png);    // assets\red.png
LV_IMG_DECLARE(ui_img_greend_png);    // assets\greend.png
LV_IMG_DECLARE(ui_img_blue_png);    // assets\blue.png
LV_IMG_DECLARE(ui_img_audio_wave_1_png);    // assets\audio_wave_1.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
