// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Print

#ifndef _PRINT_UI_H
#define _PRINT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label7;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label8;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Screen2;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label6;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_5_png);    // assets\5.png
LV_IMG_DECLARE(ui_img_17_png);    // assets\17.png
LV_IMG_DECLARE(ui_img_16_png);    // assets\16.png
LV_IMG_DECLARE(ui_img_1_png);    // assets\1.png
LV_IMG_DECLARE(ui_img_2_png);    // assets\2.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
